<a href="https://colab.research.google.com/github/Its1akub/GoogleColab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np



20.1 NumPy pole

In [4]:
a = np.array([0, 1, 2, 3])
b = np.array([0, 1, 5, 30])

print(a)
print(b)

[0 1 2 3]
[ 0  1  5 30]


20.2 NumPy vícerozměrné pole

In [5]:
brute_force = np.array([
    [0.2, 1.4412, 1.94724],   # čas
    [120, 240, 360],          # paměť (např. MB)
    [6, 8, 10]                # počet sedadel
])

monte_carlo = np.array([
    [0.22, 0.21, 0.22],
    [30, 30, 30],
    [20, 50, 100]
])

heuristika = np.array([
    [0.2, 0.342, 0.44],
    [40, 55, 70],
    [20, 40, 60]
])

In [6]:
def vypis_casovou_slozitost(nazev, data):
    casova_slozitost = data[0]   # první řádek = čas
    print(f"{nazev}, časová složitost [sec]: {casova_slozitost}")


In [7]:
vypis_casovou_slozitost("Brute force", brute_force)
vypis_casovou_slozitost("Monte carlo", monte_carlo)
vypis_casovou_slozitost("Heuristika", heuristika)


Brute force, časová složitost [sec]: [0.2     1.4412  1.94724]
Monte carlo, časová složitost [sec]: [0.22 0.21 0.22]
Heuristika, časová složitost [sec]: [0.2   0.342 0.44 ]



20.3 NumPy indexace

In [8]:
print(brute_force[1, 1:-1])
print(monte_carlo[0, -5:])


[240.]
[0.22 0.21 0.22]


In [9]:
pole = heuristika
print(pole.ndim)
print(pole.shape)
print(pole.dtype)
print(pole.itemsize)
print(pole.data)


2
(3, 3)
float64
8
