<a href="https://colab.research.google.com/github/Its1akub/GoogleColab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np



20.1 NumPy pole

In [4]:
a = np.array([0, 1, 2, 3])
b = np.array([0, 1, 5, 30])

print(a)
print(b)

[0 1 2 3]
[ 0  1  5 30]


20.2 NumPy vícerozměrné pole

In [5]:
brute_force = np.array([
    [0.2, 1.4412, 1.94724],   # čas
    [120, 240, 360],          # paměť (např. MB)
    [6, 8, 10]                # počet sedadel
])

monte_carlo = np.array([
    [0.22, 0.21, 0.22],
    [30, 30, 30],
    [20, 50, 100]
])

heuristika = np.array([
    [0.2, 0.342, 0.44],
    [40, 55, 70],
    [20, 40, 60]
])

In [6]:
def vypis_casovou_slozitost(nazev, data):
    casova_slozitost = data[0]   # první řádek = čas
    print(f"{nazev}, časová složitost [sec]: {casova_slozitost}")


In [7]:
vypis_casovou_slozitost("Brute force", brute_force)
vypis_casovou_slozitost("Monte carlo", monte_carlo)
vypis_casovou_slozitost("Heuristika", heuristika)


Brute force, časová složitost [sec]: [0.2     1.4412  1.94724]
Monte carlo, časová složitost [sec]: [0.22 0.21 0.22]
Heuristika, časová složitost [sec]: [0.2   0.342 0.44 ]



20.3 NumPy indexace

In [8]:
print(brute_force[1, 1:-1])
print(monte_carlo[0, -5:])


[240.]
[0.22 0.21 0.22]


In [9]:
pole = heuristika
print(pole.ndim)
print(pole.shape)
print(pole.dtype)
print(pole.itemsize)
print(pole.data)


2
(3, 3)
float64
8



20.4 NumPy shaping and operations

In [10]:
brute_force = np.array([1, 2, 3, 0.1932, 1.1247, 2.2435, 2243, 2124, 2143])
print(brute_force.shape)

brute_force_reshaped = brute_force.reshape(3, 3)
print(brute_force_reshaped)
print(brute_force_reshaped.shape)


(9,)
[[1.0000e+00 2.0000e+00 3.0000e+00]
 [1.9320e-01 1.1247e+00 2.2435e+00]
 [2.2430e+03 2.1240e+03 2.1430e+03]]
(3, 3)


In [11]:
velikost, spotreba_cas, spotreba_pamet = np.array_split(brute_force, 3)

print(velikost)
print(spotreba_cas)
print(spotreba_pamet)


[1. 2. 3.]
[0.1932 1.1247 2.2435]
[2243. 2124. 2143.]


In [12]:
spojene = np.concatenate((velikost, spotreba_cas, spotreba_pamet))
print(spojene)


[1.0000e+00 2.0000e+00 3.0000e+00 1.9320e-01 1.1247e+00 2.2435e+00
 2.2430e+03 2.1240e+03 2.1430e+03]


In [13]:
vysledek = np.stack((velikost, spotreba_cas, spotreba_pamet), axis=1)
print(vysledek)
print(vysledek.shape)


[[1.0000e+00 1.9320e-01 2.2430e+03]
 [2.0000e+00 1.1247e+00 2.1240e+03]
 [3.0000e+00 2.2435e+00 2.1430e+03]]
(3, 3)


In [14]:
vysledek = np.vstack((velikost, spotreba_cas, spotreba_pamet))
print(vysledek)
print(vysledek.shape)


[[1.0000e+00 2.0000e+00 3.0000e+00]
 [1.9320e-01 1.1247e+00 2.2435e+00]
 [2.2430e+03 2.1240e+03 2.1430e+03]]
(3, 3)


In [15]:
vysledek = np.hstack((velikost, spotreba_cas, spotreba_pamet))
print(vysledek)
print(vysledek.shape)


[1.0000e+00 2.0000e+00 3.0000e+00 1.9320e-01 1.1247e+00 2.2435e+00
 2.2430e+03 2.1240e+03 2.1430e+03]
(9,)


In [16]:
vysledek = np.dstack((velikost, spotreba_cas, spotreba_pamet))
print(vysledek)
print(vysledek.shape)


[[[1.0000e+00 1.9320e-01 2.2430e+03]
  [2.0000e+00 1.1247e+00 2.1240e+03]
  [3.0000e+00 2.2435e+00 2.1430e+03]]]
(1, 3, 3)



20.5 NumPy filtering and manipulating

In [17]:
data = np.array([0.1743, 0.2732, 0.3521, 0.4924])

In [18]:
filter = np.array([True, False, True, False])
nova_data = data[filter]
print("Původní data:", data)
print("Nová data:", nova_data)


Původní data: [0.1743 0.2732 0.3521 0.4924]
Nová data: [0.1743 0.3521]


In [19]:
data = data * 1000
print(data)


[174.3 273.2 352.1 492.4]


In [20]:
data = data - 1
print(data)


[173.3 272.2 351.1 491.4]


In [21]:
jine_pole = np.array([1, 2, 3, 4])
data = data + jine_pole
print(data)


[174.3 274.2 354.1 495.4]


In [22]:
pripraveny_filtr = data < 0.25
print(pripraveny_filtr)


[False False False False]



20.6 NumPy searching

In [23]:
data = np.array([20, 23, -100, -5, 30, 70, -18, 99, 81, 16,
                 45, 90, -39, -82, 75, 0, 16, 91, 48, 0, 70])

In [25]:
idx_zaporna = np.where(data < 0)
print(idx_zaporna)
print(data[idx_zaporna])


(array([ 2,  3,  6, 12, 13]),)
[-100   -5  -18  -39  -82]


In [26]:
idx_rozsah = np.where((data >= -10) & (data <= -1))
print(data[idx_rozsah])


[-5]


In [27]:
idx_kombinace = np.where(((data >= 1) & (data <= 50)) | (data < 0))
print(data[idx_kombinace])


[  20   23 -100   -5   30  -18   16   45  -39  -82   16   48]



20.7 NumPy generování náhodných čísel